name: Update gist
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update gist
        uses: ./
        env:
          TOKEN_GIST_ID: ${{ vars.TOKEN_GIST_ID }} 
          GIST_ID: ${{ vars.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STRAVA_ATHLETE_ID: ${{ vars.STRAVA_ATHLETE_ID }}
          STRAVA_CLIENT_ID: ${{ vars.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          KEY: ${{ secrets.KEY }}
